### ISSUE TITLE
cannot convert ‘std::__cxx11::basic_string<char>::iterator’ to ‘const char*’

### ISSUE THREAD

**Issue by Arndorferd** [lostallmymoney/Razer_Mouse_Linux#21] opened 2022-05-29 07:12 UTC
when running sh install.sh getting

naga.cpp:125:75: error: cannot convert ‘std::__cxx11::basic_string<char>::iterator’ to ‘const char*’
  125 |                                 commandType.erase(remove(commandType.begin(), commandType.end(), ' '), commandType.end());//Erase spaces inside 1st part of the line
      |                                                          ~~~~~~~~~~~~~~~~~^~
      |                                                                           |
      |                                                                           std::__cxx11::basic_string<char>::iterator
In file included from /usr/include/c++/12.1.0/cstdio:42,
                 from /usr/include/c++/12.1.0/ext/string_conversions.h:43,
                 from /usr/include/c++/12.1.0/bits/basic_string.h:3960,
                 from /usr/include/c++/12.1.0/string:53,
                 from /usr/include/c++/12.1.0/stdexcept:39,
                 from /usr/include/c++/12.1.0/system_error:41,
                 from /usr/include/c++/12.1.0/bits/std_mutex.h:39,
                 from /usr/include/c++/12.1.0/bits/atomic_wait.h:49,
                 from /usr/include/c++/12.1.0/bits/atomic_base.h:41,
                 from /usr/include/c++/12.1.0/atomic:41,
                 from /usr/include/c++/12.1.0/stop_token:34,
                 from /usr/include/c++/12.1.0/thread:40,
                 from fakeKeys.h:6:
/usr/include/stdio.h:152:32: note:   initializing argument 1 of ‘int remove(const char*)’
  152 | extern int remove (const char *__filename) __THROW;
      |                    ~~~~~~~~~~~~^~~~~~~~~~
Error at compile! Ensure you have g++ installed. !!!Aborting!!!

**Comment by lostallmymoney** [comment] 2022-05-30 00:05
Looking into it by tmr
________________________________
From: Arndorferd ***@***.***>
Sent: Sunday, May 29, 2022 3:12:53 AM
To: lostallmymoney/Razer_Mouse_Linux ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lostallmymoney/Razer_Mouse_Linux] cannot convert ‘std::__cxx11::basic_string<char>::iterator’ to ‘const char*’ (Issue #21)


when running sh install.sh getting

naga.cpp:125:75: error: cannot convert ‘std::__cxx11::basic_string::iterator’ to ‘const char*’
125 | commandType.erase(remove(commandType.begin(), commandType.end(), ' '), commandType.end());//Erase spaces inside 1st part of the line
| ~~~~~~~~~~~~~~~~~^~
| |
| std::__cxx11::basic_string::iterator
In file included from /usr/include/c++/12.1.0/cstdio:42,
from /usr/include/c++/12.1.0/ext/string_conversions.h:43,
from /usr/include/c++/12.1.0/bits/basic_string.h:3960,
from /usr/include/c++/12.1.0/string:53,
from /usr/include/c++/12.1.0/stdexcept:39,
from /usr/include/c++/12.1.0/system_error:41,
from /usr/include/c++/12.1.0/bits/std_mutex.h:39,
from /usr/include/c++/12.1.0/bits/atomic_wait.h:49,
from /usr/include/c++/12.1.0/bits/atomic_base.h:41,
from /usr/include/c++/12.1.0/atomic:41,
from /usr/include/c++/12.1.0/stop_token:34,
from /usr/include/c++/12.1.0/thread:40,
from fakeKeys.h:6:
/usr/include/stdio.h:152:32: note: initializing argument 1 of ‘int remove(const char*)’
152 | extern int remove (const char *__filename) __THROW;
| ~~~~~~~~~~~~^~~~~~~~~~
Error at compile! Ensure you have g++ installed. !!!Aborting!!!

**Comment by lostallmymoney** [comment] 2022-09-03 05:28
Can you guys tell me what you did to fix ? I did not have issue on my end.. I think it might be compiler version, changing a type somewhere should work then

**Comment by yukiqt** [comment] 2022-10-12 11:38
This can be fixed by adding `#include <algorithm>` near the top of `src/naga.cpp`

**Comment by lostallmymoney** [comment] 2022-11-25 04:34
Hey I think trying to cast the space like that (const char)" " might work or just (char).

**Comment by AlphaOneProject** [comment] 2022-12-27 00:30
Had the same issue, after adding `#include <bits/stdc++.h>` it finally compiled! (far from a C++ dev, just trying things out until I got it working :/)

**Comment by AlphaOneProject** [comment] 2022-12-27 13:03
Done on Arch with a Naga Trinity btw, just in case it matters.

**Comment by traumweh** [comment] 2023-01-08 18:15
The problem is that the function
```c++
template <class ForwardIterator, class T>  ForwardIterator remove (ForwardIterator first, ForwardIterator last, const T& val);
```
is from the algorithm header-file, which isn't included. It probably gets included indirectly on older versions. Adding `#include <algorithm>` should resolve the issue.

**Closed** 2023-03-13 05:44 UTC
